name: 功能请求
description: 为 Photoo 提出一项新的功能。
title: （将此栏【替换】为你的标题）
labels: ["新功能"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您贡献您的想法。请在上面的文本框⬆起一个能够清晰概括此功能的标题，便于开发者了解您的想法。
        
        > [!important]
        > 重要：如果您想要提出 **多项功能**，请为每一个功能开一个单独的 issue。

  - type: checkboxes
    id: checklist
    attributes:
      label: 检查清单
      description: 在开始反馈这个问题之前，请先检查：
      options:
        - label: 我已更新到最新版 ![最新的版本号](https://github.com/xigua222/photoo?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://github.com/xigua222/photoo?style=flat-square&label=) 测试，并看过 [最新提交](https://github.com/xigua222/photoo/commits/dev/)，确认这一 Bug 还没有修复。我也已在 [Issues](https://github.com/xigua222/photoo/issues?q=type%3ABug) 中检索，确认这一 Bug 未被提交过。
          required: true
        - label: 我已经仔细阅读过选项里的内容，并且知道这个选项不用勾选。
        - label: 我已知晓由于开发者时间精力有限，我提交的功能请求可能需要比较久的时间才能实现。
          required: true
  - type: markdown
    attributes: 
      value: |
        > [!note]
        > 上传附件时**请优先使用 GitHub 的附件系统上传附件**，将需要上传的附件粘贴或拖动到撰写区域即可上传。多个文件可打包为 zip 格式后上传。**尽量避免使用需要登陆或安装客户端才能接收附件的网盘（如\*度网盘、\*克网盘）上传附件**，以避免开发者因不具有对应网盘客户端或账户而延误问题诊断。
  - type: textarea
    id: back
    attributes:
      label: 背景与动机
      description: 为什么你需要这个功能？这个功能对你和其他用户有多重要？
    validations:
      required: true
  - type: textarea
    id: req
    attributes:
      label: 想要实现或优化的功能
      description: 详细地描述一下你想要的功能，描述的越具体，采纳的可能性越高。
    validations:
      required: true
  - type: checkboxes
    id: revision
    attributes:
      label: 最后一步
      description: 回顾您的回答
      options:
        - label: 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

          required: true
