package com.voicelike.app

import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf
import androidx.compose.runtime.remember

enum class AppLanguage(val code: String, val displayName: String) {
    English("en", "English"),
    SimplifiedChinese("zh-SC", "简体中文"),
    TraditionalChinese("zh-TC", "繁体中文"),
    Korean("ko", "한국어"),
    Japanese("ja", "日本語"),
    French("fr", "Français"),
    German("de", "Deutsch"),
    Italian("it", "Italiano"),
    Portuguese("pt", "Português"),
    Spanish("es", "Español"),
    Russian("ru", "Русский"),
    Thai("th", "ไทย"),
    Vietnamese("vi", "Tiếng Việt"),
    Indonesian("id", "Bahasa Indonesia"),
    Arabic("ar", "العربية")
}

data class LocalizedStrings(
    val undo: String,
    val clean: String,
    val stats: String,
    val skip: String,
    val trash: String,
    val live: String,
    val unknownLocation: String,
    val camera: String,
    val location: String,
    val iso: String,
    val shutter: String,
    val date: String,
    val size: String,
    val resolution: String,
    val filename: String,
    val settings: String,
    val language: String,
    val processed: String,
    val deleted: String,
    val skippedLabel: String,
    val savedSpace: String,
    val emptyStateTitle: String,
    val emptyStateSubtitle: String,
    val emptyStateButton: String,
    val permissionsNeed: String,
    val timeSaved: String,
    val totalProcessed: String,
    val ofGallery: String,
    val savedSpaceRatioFormat: String, // Replaces 'of'
    val pressAgainToExit: String,
    val deleteReviewTitle: String,
    val deleteReviewSubtitle: String,
    val cancel: String,
    val delete: String,
    val similar: String,
    val noSimilarPhotosFound: String,
    val scanning: String,
    val stop: String,
    // New Strings
    val keepSelected: String,
    val keepAll: String,
    val deleteAll: String,
    val selectBest: String,
    val similarPhotosDone: String,
    val done: String,
    val noSimilarPhotos: String,
    val likes: String,
    val viewLikes: String,
    val months: List<String>,
    // Smart Organize
    val smartOrganizeTitle: String,
    val noClustersFound: String,
    val moveTo: String,
    val move: String,
    val collapse: String,
    val viewAll: String,
    // Monthly & Language
    val monthly: String,
    val monthlyTitle: String,
    val monthlyDoneTitle: String,
    val monthlyDoneButton: String,
    val selectLanguage: String,
    val back: String,
    // Privacy
    val privacyTitle: String,
    val privacyButton: String,
    val privacySection1Title: String,
    val privacySection1Content: String,
    val privacySection2Title: String,
    val privacySection2Content: String,
    val privacySection3Title: String,
    val privacySection3Content: String,
    val privacySection4Title: String,
    val privacySection4Content: String,
    val onboardingWelcomeTitle: String,
    val onboardingWelcomeSubtitle: String,
    val videoCompressThresholdLabel: String,
    val onboardingNext: String,
    val onboardingBack: String,
    val onboardingLanguageTitle: String,
    val onboardingLanguageSubtitle: String,
    val onboardingPermissionTitle: String,
    val onboardingPermissionSubtitle: String,
    val onboardingPermissionButton: String,
    val onboardingPermissionGranted: String,
    val onboardingStartTitle: String,
    val onboardingStartSubtitle: String,
    val onboardingStartButton: String,
    // Settings
    val batchSize: String,
    val queueOrder: String,
    val orderRandom: String,
    val orderTime: String,
    val releaseKept: String,
    val releaseKeptDesc: String,
    val released: String,
    val version: String,
    val copyright: String,
    // Release Dialog
    val releaseDialogTitle: String,
    val releaseDialogContent: String,
    val confirm: String,
    // Mute
    val muteVideos: String,
    // Filter
    val filterTitle: String,
    val filterType: String,
    val filterFolder: String,
    val apply: String,
    val filterAll: String,
    val filterImage: String,
    val filterVideo: String,
    val filterLive: String,
    val viewTrash: String,
    val filterCompletedTitle: String,
    val filterCompletedSubtitle: String,
    val reviewAgain: String,
    val changeFilter: String,
    val selectMonth: String,
    val filterMonth: String,
    // Low Quality
    val lowQuality: String,
    val blur: String,
    val underexposed: String,
    val overexposed: String,
    val closedEyes: String,
    val smallFile: String,
    val lowResolution: String,
    val scanLowQuality: String,
    val noLowQualityFound: String,
    val lowQualityDone: String,
    val solidColor: String,
    // Deep Organize
    val deepOrganizeTitle: String,
    val deepOrganizeScanning: String,
    val deepOrganizeComplete: String,
    val deepOrganizeScanningDesc: String,
    val scanningWait: String,
    val scanningDescriptionDetailed: String,
    val exit: String,
    val similarPhotosSubtitle: String,
    val smartOrganizeSubtitle: String,
    val lowQualitySubtitle: String,
    val videoCompressTitle: String,
    val videoCompressSubtitle: String,
    val videoCompressWarningTitle: String,
    val videoCompressWarningBody: String,
    val videoCompressTargetLabel: String,
    val videoCompressBitrateLow: String,
    val videoCompressBitrateBalanced: String,
    val videoCompressBitrateHigh: String,
    val videoCompressEstimate: String,
    val videoCompressTimes: String,
    val videoCompressResultTitle: String,
    val videoCompressResultSaved: String,
    val videoCompressResultCount: String,
    val videoCompressDeleteOriginal: String,
    val videoCompressKeepOriginal: String,
    val videoCompressDeleteConfirmTitle: String,
    val videoCompressDeleteConfirmBody: String,
    val videoCompressBefore: String,
    val videoCompressAfter: String,
    val videoCompressRatio: String,
    val videoCompressAction: String,
    val videoCompressing: String,
    val videoCompressSelectHint: String,
    val videoCompressError: String,
    val imageCompressTitle: String,
    val imageCompressSubtitle: String,
    val imageCompressWarningTitle: String,
    val imageCompressWarningBody: String,
    val imageCompressThresholdLabel: String,
    val imageCompressResultTitle: String,
    val imageCompressResultSaved: String,
    val imageCompressResultCount: String,
    val imageCompressDeleteOriginal: String,
    val imageCompressKeepOriginal: String,
    val imageCompressBefore: String,
    val imageCompressAfter: String,
    val imageCompressRatio: String,
    val imageCompressAction: String,
    val imageCompressing: String,
    val imageCompressSelectHint: String,
    val imageCompressError: String,
    val imageCompressOriginalLabel: String,
    val imageCompressOriginalSize: String,
    val imageCompressSelectAll: String,
    val imageCompressSelected: String,
    // Likes View
    val commentPlaceholder: String,
    val commentsHeader: String,
    val commentUser: String,
    val noLikes: String,
    val removeLikeTitle: String,
    val removeLikeMessage: String,
    val remove: String,
    val send: String,
    val share: String,
    val comment: String,
    val removeLike: String,
    // Avatar
    val avatar: String,
    val avatarBoy: String,
    val avatarGirl: String,
    val commentUserMe: String,
    val deleteCommentTitle: String,
    val deleteCommentMessage: String,
    val copyComment: String,
    val commentCopied: String,
    // Holidays
    val holidayNewYear: String,
    val holidayValentines: String,
    val holidayChildrens: String,
    val holidayLaborDay: String,
    val holidayNationalDay: String,
    val holidaySpringFestival: String,
    val holidayDragonBoat: String,
    val holidayMidAutumn: String,
    val groupPhotosTitle: String,
    // Shooting Stats
    val shootingStatsTitle: String,
    val shootingStatsYear: String,
    val shootingStatsMonth: String,
    val shootingStatsSummary: String,
    val shootingStatsSummaryMonth: String,
    val shootingStatsItems: String,
    val shootingStatsVideoDuration: String,
    val shootingStatsMovies: String,
    val shootingStatsShortDrama: String,
    val shootingStatsTvDrama: String,
    val shootingStatsScreenshots: String,
    val shootingStatsSelfies: String,
    val shootingStatsMostActiveDay: String,
    val shootingStatsVideoTitle: String,
    val shootingStatsActiveDayTitle: String,
    val shootingStatsLocationTitle: String,
    val shootingStatsLocationPlaces: String,
    val shootingStatsHeatmapTitle: String,
    val shootingStatsHeatmapLess: String,
    val shootingStatsHeatmapMore: String,
    val soundEffects: String,
    val haptics: String,
    val comboAnimation: String,
    val newFolder: String,
    val createNewFolder: String,
    val folderName: String,
    val create: String,
    val undoSuccess: String,
    val readyForNextBatch: String,
    val privacyPolicy: String,
    val termsOfService: String,
    val agreeToTerms: String,
    val manageFilesPermission: String,
    val manageFilesPermissionDesc: String,
    val continueOrganizing: String,
    val currentFolder: String,
    val openSourceLicenses: String? = null
)

val StringsEn = LocalizedStrings(
    undo = "Undo",
    clean = "Clean",
    stats = "Stats",
    skip = "KEEP",
    trash = "TRASH",
    live = "LIVE",
    unknownLocation = "Unknown Location",
    camera = "CAMERA",
    location = "LOCATION",
    iso = "ISO",
    shutter = "SHUTTER",
    date = "DATE",
    size = "SIZE",
    resolution = "RESOLUTION",
    filename = "FILENAME",
    settings = "Settings",
    language = "Language",
    processed = "Processed",
    deleted = "Deleted",
    skippedLabel = "Skipped",
    savedSpace = "Saved Space",
    emptyStateTitle = "All Caught Up!",
    emptyStateSubtitle = "You've organized this batch of media.",
    emptyStateButton = "Load More",
    permissionsNeed = "Need Permissions to access media",
    timeSaved = "Time Saved",
    totalProcessed = "Total Processed",
    ofGallery = "of Gallery",
    savedSpaceRatioFormat = "%1\$s%% of %2\$sGB",
    pressAgainToExit = "Press back again to exit",
    deleteReviewTitle = "Review Deletion",
    deleteReviewSubtitle = "Select items to delete. Unselected items will be kept.",
    cancel = "Cancel",
    delete = "Delete",
    similar = "Similar",
    noSimilarPhotosFound = "No similar photos found",
    scanning = "Scanning...",
    stop = "Stop",
    keepSelected = "Keep Selected",
    keepAll = "Keep All",
    deleteAll = "Delete All",
    selectBest = "Select the best one to keep.",
    similarPhotosDone = "You're all caught up!",
    done = "Done",
    noSimilarPhotos = "No similar photos found",
    likes = "Likes",
    viewLikes = "View Favorites",
    months = listOf("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"),
    smartOrganizeTitle = "Smart Organize",
    noClustersFound = "No suggestions found",
    moveTo = "Move to",
    move = "Move",
    collapse = "Collapse",
    viewAll = "View All",
    monthly = "Monthly",
    monthlyTitle = "Monthly Review",
    monthlyDoneTitle = "Review Complete",
    monthlyDoneButton = "Back to Gallery",
    selectLanguage = "Select Language",
    back = "Back",
    privacyTitle = "Privacy Policy",
    privacyButton = "Privacy",
    privacySection1Title = "Local Processing",
    privacySection1Content = "All analysis (Face Detection, Similarity, Quality) happens directly on your device. Your photos are never uploaded to any server.",
    privacySection2Title = "Data Usage",
    privacySection2Content = "We only access your media library to help you organize it. No personal data is collected or shared.",
    privacySection3Title = "Permissions",
    privacySection3Content = "We require storage access to scan and manage your photos. You can revoke this at any time in system settings.",
    privacySection4Title = "Open Source & Auditable",
    privacySection4Content = "photoo is 'Source Available' software. You can review the code to verify our privacy claims. We are committed to transparency.",
    onboardingWelcomeTitle = "Welcome to photoo",
    onboardingWelcomeSubtitle = "Organize, compress, and keep your memories tidy in minutes.",
    onboardingNext = "Next",
    onboardingBack = "Back",
    onboardingLanguageTitle = "Choose your language",
    onboardingLanguageSubtitle = "Default is your device language. You can change anytime.",
    onboardingPermissionTitle = "Media access",
    onboardingPermissionSubtitle = "We need access to your photos and videos to organize and compress.",
    onboardingPermissionButton = "Grant permission",
    onboardingPermissionGranted = "Permission granted",
    onboardingStartTitle = "All set",
    onboardingStartSubtitle = "You're ready to start using photoo.",
    onboardingStartButton = "Start",
    batchSize = "Batch Size",
    queueOrder = "Queue Order",
    orderRandom = "Random",
    orderTime = "Time",
    releaseKept = "Release Processed Photos",
    releaseKeptDesc = "Reset processed items back to the queue",
    released = "Released!",
    version = "Version",
    copyright = "©superwatermelon",
    releaseDialogTitle = "Release Processed Photos?",
    releaseDialogContent = "This will make all photos you've previously processed appear in the queue again.",
    confirm = "Confirm",
    muteVideos = "Mute Videos & Live Photos",
    soundEffects = "Sound Effects",
    haptics = "Haptic Feedback",
    comboAnimation = "Combo Animation",
    filterTitle = "Filter Media",
    filterType = "Type",
    filterFolder = "Folder",
    apply = "Apply",
    filterAll = "All",
    filterImage = "Images",
    filterVideo = "Videos",
    filterLive = "Live Photos",
    viewTrash = "View Trash Queue",
    filterCompletedTitle = "Filter Completed",
    filterCompletedSubtitle = "You've reviewed all items in %1\$s.",
    reviewAgain = "Review Again (Release All)",
    changeFilter = "Change Filter",
    selectMonth = "Select Month",
    filterMonth = "Month",
    lowQuality = "Low Quality",
    blur = "Blurry",
    underexposed = "Dark",
    overexposed = "Bright",
    closedEyes = "Closed Eyes",
    smallFile = "Small File",
    lowResolution = "Low Res",
    scanLowQuality = "Scan Low Quality",
    noLowQualityFound = "No low quality items found",
    lowQualityDone = "Scan Complete",
    solidColor = "Solid Color",
    deepOrganizeTitle = "Deep Organize",
    deepOrganizeScanning = "Scanning...",
    deepOrganizeComplete = "Scan Complete",
    deepOrganizeScanningDesc = "Analyzing your gallery...",
    scanningWait = "Please wait...",
    scanningDescriptionDetailed = "This may take about %d minutes depending on your gallery size. You can exit and let it run in the background.",
    exit = "Exit",
    similarPhotosSubtitle = "Clean up duplicates",
    smartOrganizeSubtitle = "Group by events",
    lowQualitySubtitle = "Remove bad shots",
    videoCompressTitle = "Video Compression",
    videoCompressSubtitle = "Reduce size with minimal quality loss",
    videoCompressWarningTitle = "Quality Warning",
    videoCompressWarningBody = "Compression may slightly reduce clarity and bitrate, but most videos still look good on phones and sharing. Try a few first, then batch if you’re satisfied.",
    videoCompressTargetLabel = "Target Bitrate",
    videoCompressBitrateLow = "Smaller",
    videoCompressBitrateBalanced = "Balanced",
    videoCompressBitrateHigh = "Clearer",
    videoCompressEstimate = "Estimated",
    videoCompressTimes = "Compressed %d times",
    videoCompressResultTitle = "Compression Complete",
    videoCompressResultSaved = "Space Saved",
    videoCompressResultCount = "Videos Compressed",
    videoCompressDeleteOriginal = "Delete Originals",
    videoCompressKeepOriginal = "Keep Originals",
    videoCompressDeleteConfirmTitle = "Delete Original Videos?",
    videoCompressDeleteConfirmBody = "Compressed copies are saved. Deleting originals cannot be undone.",
    videoCompressBefore = "Original",
    videoCompressAfter = "Compressed",
    videoCompressRatio = "Compression Ratio",
    videoCompressAction = "Start Compression",
    videoCompressing = "Compressing",
    videoCompressSelectHint = "Select videos to compress",
    videoCompressError = "Compression failed",
    imageCompressTitle = "Image Compression",
    imageCompressSubtitle = "Compress photos to save space",
    imageCompressWarningTitle = "Quality Notice",
    imageCompressWarningBody = "Compression reduces quality. Try a few images first, then batch if satisfied.",
    imageCompressThresholdLabel = "Filter Threshold",
    videoCompressThresholdLabel = "Filter Threshold",
    imageCompressResultTitle = "Compression Complete",
    imageCompressResultSaved = "Space Saved",
    imageCompressResultCount = "Images Compressed",
    imageCompressDeleteOriginal = "Delete Originals",
    imageCompressKeepOriginal = "Keep Originals",
    imageCompressBefore = "Before",
    imageCompressAfter = "After",
    imageCompressRatio = "Compression Ratio",
    imageCompressAction = "Start Compression",
    imageCompressing = "Compressing",
    imageCompressSelectHint = "Select images to compress",
    imageCompressError = "Compression failed",
    imageCompressOriginalLabel = "ORIGINAL",
    imageCompressOriginalSize = "Keep size",
    imageCompressSelectAll = "Select Month",
    imageCompressSelected = "All Selected",
    commentPlaceholder = "Add a comment...",
    commentsHeader = "Comments",
    commentUser = "You",
    noLikes = "No likes yet",
    removeLikeTitle = "Remove Like?",
    removeLikeMessage = "This will remove this item from your favorites.",
    remove = "Remove",
    send = "Send",
    share = "Share",
    comment = "Comment",
    removeLike = "Remove Like",
    avatar = "Avatar",
    avatarBoy = "Boy",
    avatarGirl = "Girl",
    commentUserMe = "Me",
    deleteCommentTitle = "Delete Comment?",
    deleteCommentMessage = "Are you sure you want to delete this comment?",
    copyComment = "Copy",
    commentCopied = "Comment copied to clipboard",
    holidayNewYear = "New Year's Day",
    holidayValentines = "Valentine's Day",
    holidayChildrens = "Children's Day",
    holidayLaborDay = "Labor Day Holiday",
    holidayNationalDay = "National Day Holiday",
    holidaySpringFestival = "Spring Festival",
    holidayDragonBoat = "Dragon Boat Festival",
    holidayMidAutumn = "Mid-Autumn Festival",
    groupPhotosTitle = "Group Photos",
    shootingStatsTitle = "Album Insights",
    shootingStatsYear = "Year",
    shootingStatsMonth = "Month",
    shootingStatsSummary = "In %1\$s, you recorded %2\$s moments.",
    shootingStatsSummaryMonth = "In %1\$s, you recorded %2\$s moments.",
    shootingStatsItems = "%1\$s Photos | %2\$s Videos",
    shootingStatsVideoDuration = "Total Video: %1\$s mins",
    shootingStatsMovies = "Equiv. to watching %1\$s movies",
    shootingStatsShortDrama = "Equiv. to %1\$s short dramas",
    shootingStatsTvDrama = "Equiv. to %1\$s TV episodes",
    shootingStatsScreenshots = "Screenshots",
    shootingStatsSelfies = "Selfies",
    shootingStatsMostActiveDay = "Most Active: %1\$s (%2\$s items)",
    shootingStatsVideoTitle = "Video",
    shootingStatsActiveDayTitle = "Active Day",
    shootingStatsLocationTitle = "Location",
    shootingStatsLocationPlaces = "%1\$s Places",
    shootingStatsHeatmapTitle = "Activity Heatmap",
    shootingStatsHeatmapLess = "Less",
    shootingStatsHeatmapMore = "More",
    newFolder = "New Folder",
    createNewFolder = "Create New Folder",
    folderName = "Folder Name",
    create = "Create",
    undoSuccess = "Undone",
    readyForNextBatch = "Ready for the next batch? (%1\$d items remaining)",
    continueOrganizing = "Continue Organizing",
    privacyPolicy = "Privacy Policy",
    termsOfService = "Terms of Service",
    agreeToTerms = "I agree to the Terms of Service and Privacy Policy",
    manageFilesPermission = "Manage All Files",
    manageFilesPermissionDesc = "Required to move photos into folders and organize your gallery structure.",
    currentFolder = "Current Folder",
    openSourceLicenses = "Open Source Licenses"
)

val StringsZh = LocalizedStrings(
    undo = "撤回",
    clean = "清理",
    stats = "统计",
    skip = "保留", // Changed from "保存" to "保留"
    trash = "删除",
    live = "实况",
    unknownLocation = "未知位置",
    camera = "相机",
    location = "位置",
    iso = "ISO",
    shutter = "快门",
    date = "日期",
    size = "大小",
    resolution = "分辨率",
    filename = "文件名",
    settings = "设置",
    language = "语言",
    processed = "已处理",
    deleted = "已删除",
    skippedLabel = "已跳过",
    savedSpace = "节省空间",
    emptyStateTitle = "全部搞定！",
    emptyStateSubtitle = "你已整理完这一批媒体文件。",
    emptyStateButton = "加载更多",
    permissionsNeed = "需要访问媒体文件的权限",
    timeSaved = "节省时间",
    totalProcessed = "总共处理",
    ofGallery = "相册占比",
    savedSpaceRatioFormat = "%1\$s%% (共 %2\$sGB)",
    pressAgainToExit = "再按一次退出",
    deleteReviewTitle = "删除确认",
    deleteReviewSubtitle = "勾选需要删除的照片，取消勾选的照片将会被保留。",
    cancel = "取消",
    delete = "删除",
    similar = "相似",
    noSimilarPhotosFound = "未发现相似图片",
    scanning = "扫描中...",
    stop = "停止",
    keepSelected = "保留选中",
    keepAll = "保留所有",
    deleteAll = "删除所有",
    selectBest = "选择一张最好的保留，其余删除。",
    similarPhotosDone = "所有相似图片已处理完毕！",
    done = "完成",
    noSimilarPhotos = "未找到类似照片",
    likes = "喜欢",
    viewLikes = "查看喜爱",
    months = listOf("一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"),
    smartOrganizeTitle = "智能归档",
    noClustersFound = "暂无归档建议",
    moveTo = "移至",
    move = "移动",
    collapse = "收起",
    viewAll = "查看全部",
    monthly = "按月整理",
    monthlyTitle = "按月整理",
    monthlyDoneTitle = "本月已整理完毕！",
    monthlyDoneButton = "返回按月列表",
    selectLanguage = "选择语言",
    back = "返回",
    privacyTitle = "隐私保护说明",
    privacyButton = "隐私",
    privacySection1Title = "数据收集",
    privacySection1Content = "我们仅访问您的照片和视频以帮助您整理。我们需要存储权限仅用于此目的。我们不收集任何个人信息。",
    privacySection2Title = "隐私保护",
    privacySection2Content = "我们完全离线运行。无需联网，无需登录，我们不追踪用户行为或进行用户分析。",
    privacySection3Title = "数据安全",
    privacySection3Content = "您的数据仅保留在设备上。所有处理均在本地进行，确保您的照片永远不会离开您的手机。",
    privacySection4Title = "开源可审计",
    privacySection4Content = "photoo 是“源码可用”软件。您可以审查代码以验证我们的隐私承诺。我们致力于透明化。",
    onboardingWelcomeTitle = "欢迎使用 photoo",
    onboardingWelcomeSubtitle = "几分钟内整理与压缩你的相册。",
    onboardingNext = "下一步",
    onboardingBack = "上一步",
    onboardingLanguageTitle = "选择语言",
    onboardingLanguageSubtitle = "默认设备语言，可随时切换。",
    onboardingPermissionTitle = "授权访问",
    onboardingPermissionSubtitle = "需要访问照片与视频用于本地整理与压缩。",
    onboardingPermissionButton = "授权",
    onboardingPermissionGranted = "已授权",
    onboardingStartTitle = "准备就绪",
    onboardingStartSubtitle = "现在可以开始使用 photoo。",
    onboardingStartButton = "开始使用",
    batchSize = "批量大小",
    queueOrder = "队列顺序",
    orderRandom = "随机",
    orderTime = "时间",
    releaseKept = "释放已处理照片",
    releaseKeptDesc = "将已处理的照片重置回队列",
    released = "已释放",
    version = "版本",
    copyright = "©超级西瓜",
    releaseDialogTitle = "释放已处理照片？",
    releaseDialogContent = "这将把所有已处理的照片重置回队列。确定吗？",
    confirm = "确认",
    muteVideos = "视频和动态图片默认静音",
    soundEffects = "音效",
    haptics = "震动反馈",
    comboAnimation = "连胜动画",
    filterTitle = "筛选",
    filterType = "媒体类型",
    filterFolder = "文件夹",
    apply = "应用",
    filterAll = "全部",
    filterImage = "图片",
    filterVideo = "视频",
    filterLive = "实况",
    viewTrash = "查看删除队列",
    filterCompletedTitle = "筛选完成",
    filterCompletedSubtitle = "您已整理完 %1\$s 中的所有项目。",
    reviewAgain = "重新整理（释放全部）",
    changeFilter = "更换筛选",
    selectMonth = "选择月份",
    filterMonth = "月份",
    lowQuality = "低质量",
    blur = "模糊",
    underexposed = "曝光不足",
    overexposed = "曝光过度",
    closedEyes = "闭眼",
    smallFile = "文件过小",
    lowResolution = "分辨率低",
    scanLowQuality = "扫描低质量",
    noLowQualityFound = "未发现低质量照片",
    lowQualityDone = "所有低质量照片已处理完毕！",
    solidColor = "纯色",
    deepOrganizeTitle = "深度整理",
    deepOrganizeScanning = "扫描相册中...",
    deepOrganizeComplete = "扫描完成",
    deepOrganizeScanningDesc = "正在分析照片质量、相似度和事件。",
    scanningWait = "请稍候...",
    scanningDescriptionDetailed = "根据照片数量，这可能需要约%d分钟。您可以退出页面，程序将在后台继续运行。",
    exit = "退出",
    similarPhotosSubtitle = "查找并清理重复照片",
    smartOrganizeSubtitle = "按事件和地点分组照片",
    lowQualitySubtitle = "模糊、黑暗和质量差的照片",
    videoCompressTitle = "视频压缩",
    videoCompressSubtitle = "显著减小体积且不损失太多画质",
    videoCompressWarningTitle = "清晰度提示",
    videoCompressWarningBody = "压缩会降低清晰度与码率，但多数场景仍可接受。建议先试少量视频，满意后再批量处理；画面越复杂，节省空间越多。",
    videoCompressTargetLabel = "目标码率",
    videoCompressBitrateLow = "更小体积",
    videoCompressBitrateBalanced = "均衡",
    videoCompressBitrateHigh = "更清晰",
    videoCompressEstimate = "预计",
    videoCompressTimes = "已压缩 %d 次",
    videoCompressResultTitle = "压缩完成",
    videoCompressResultSaved = "节省空间",
    videoCompressResultCount = "已压缩视频",
    videoCompressDeleteOriginal = "删除原视频",
    videoCompressKeepOriginal = "保留原视频",
    videoCompressDeleteConfirmTitle = "删除原视频？",
    videoCompressDeleteConfirmBody = "压缩视频已保存，删除后将无法恢复。",
    videoCompressBefore = "原大小",
    videoCompressAfter = "压缩后",
    videoCompressRatio = "压缩比例",
    videoCompressAction = "开始压缩",
    videoCompressing = "压缩中",
    videoCompressSelectHint = "请选择要压缩的视频",
    videoCompressError = "压缩失败",
    imageCompressTitle = "图片压缩",
    imageCompressSubtitle = "压缩图片，释放空间",
    imageCompressWarningTitle = "清晰度提示",
    imageCompressWarningBody = "压缩会降低清晰度，建议先试少量图片，满意后再批量处理。",
    imageCompressThresholdLabel = "筛选阈值",
    videoCompressThresholdLabel = "筛选阈值",
    imageCompressResultTitle = "压缩完成",
    imageCompressResultSaved = "节省空间",
    imageCompressResultCount = "已压缩图片",
    imageCompressDeleteOriginal = "删除原图片",
    imageCompressKeepOriginal = "保留原图片",
    imageCompressBefore = "原大小",
    imageCompressAfter = "压缩后",
    imageCompressRatio = "压缩比例",
    imageCompressAction = "开始压缩",
    imageCompressing = "压缩中",
    imageCompressSelectHint = "请选择要压缩的图片",
    imageCompressError = "压缩失败",
    imageCompressOriginalLabel = "原尺寸",
    imageCompressOriginalSize = "保持尺寸",
    imageCompressSelectAll = "全选本月",
    imageCompressSelected = "已全选",
    commentPlaceholder = "添加评论...",
    commentsHeader = "评论",
    commentUser = "你",
    noLikes = "暂无喜欢",
    removeLikeTitle = "移出喜欢",
    removeLikeMessage = "确认将此项移出喜欢列表吗？",
    remove = "移除",
    send = "发送",
    share = "分享",
    comment = "评论",
    removeLike = "移除喜欢",
    avatar = "头像",
    avatarBoy = "男生",
    avatarGirl = "女生",
    commentUserMe = "我",
    deleteCommentTitle = "删除评论？",
    deleteCommentMessage = "确定要删除这条评论吗？",
    copyComment = "复制",
    commentCopied = "评论已复制",
    holidayNewYear = "元旦",
    holidayValentines = "情人节",
    holidayChildrens = "儿童节",
    holidayLaborDay = "五一劳动节",
    holidayNationalDay = "国庆黄金周",
    holidaySpringFestival = "春节",
    holidayDragonBoat = "端午节",
    holidayMidAutumn = "中秋节",
    groupPhotosTitle = "合影聚合",
    shootingStatsTitle = "相册洞察",
    shootingStatsYear = "年",
    shootingStatsMonth = "月",
    shootingStatsSummary = "%1\$s年，你记录了 %2\$s 个瞬间。",
    shootingStatsSummaryMonth = "%1\$s，你记录了 %2\$s 个瞬间。",
    shootingStatsItems = "%1\$s 照片 | %2\$s 视频",
    shootingStatsVideoDuration = "视频总长 %1\$s 分钟",
    shootingStatsMovies = "相当于看了 %1\$s 部电影",
    shootingStatsShortDrama = "相当于看了 %1\$s 集短剧",
    shootingStatsTvDrama = "相当于看了 %1\$s 集电视剧",
    shootingStatsScreenshots = "截图",
    shootingStatsSelfies = "自拍",
    shootingStatsMostActiveDay = "最活跃的一天: %1\$s (%2\$s 张)",
    shootingStatsVideoTitle = "视频",
    shootingStatsActiveDayTitle = "活跃天",
    shootingStatsLocationTitle = "地点",
    shootingStatsLocationPlaces = "%1\$s 个地点",
    shootingStatsHeatmapTitle = "活跃热力图",
    shootingStatsHeatmapLess = "少",
    shootingStatsHeatmapMore = "多",
    newFolder = "新建文件夹",
    createNewFolder = "创建新文件夹",
    folderName = "文件夹名称",
    create = "创建",
    undoSuccess = "已撤销",
    readyForNextBatch = "准备好处理下一批了吗？（剩余 %1\$d 项）",
    continueOrganizing = "继续整理",
    privacyPolicy = "隐私协议",
    termsOfService = "用户协议",
    agreeToTerms = "我已阅读并同意用户协议和隐私协议",
    manageFilesPermission = "管理所有文件",
    manageFilesPermissionDesc = "需要此权限才能将照片移动到文件夹并整理您的相册结构。",
    currentFolder = "当前文件夹",
    openSourceLicenses = "开源许可"
)

val StringsKo = LocalizedStrings(
    undo = "실행 취소",
    clean = "청소",
    stats = "통계",
    skip = "보관", // Changed from "저장" to "보관" (Keep/Archive)
    trash = "삭제",
    live = "라이브",
    unknownLocation = "알 수 없는 위치",
    camera = "카메라",
    location = "위치",
    iso = "ISO",
    shutter = "셔터",
    date = "날짜",
    size = "크기",
    resolution = "해상도",
    filename = "파일명",
    settings = "설정",
    language = "언어",
    processed = "처리됨",
    deleted = "삭제됨",
    skippedLabel = "건너뜀",
    savedSpace = "절약된 공간",
    emptyStateTitle = "모두 완료!",
    emptyStateSubtitle = "이 배치의 미디어를 정리했습니다.",
    emptyStateButton = "더 불러오기",
    permissionsNeed = "미디어 액세스 권한 필요",
    timeSaved = "절약된 시간",
    totalProcessed = "총 처리됨",
    ofGallery = "갤러리 비율",
    savedSpaceRatioFormat = "%1\$s%% (총 %2\$sGB)",
    pressAgainToExit = "한 번 더 누르면 종료됩니다",
    deleteReviewTitle = "삭제 확인",
    deleteReviewSubtitle = "삭제할 항목을 선택하세요. 선택하지 않은 항목은 유지됩니다.",
    cancel = "취소",
    delete = "삭제",
    similar = "유사",
    noSimilarPhotosFound = "유사한 사진을 찾을 수 없습니다",
    scanning = "스캔 중...",
    stop = "중지",
    keepSelected = "선택 항목 유지",
    keepAll = "모두 유지",
    deleteAll = "모두 삭제",
    selectBest = "가장 좋은 사진을 선택하세요.",
    similarPhotosDone = "모든 유사 사진이 처리되었습니다!",
    done = "완료",
    noSimilarPhotos = "유사한 사진을 찾을 수 없습니다",
    likes = "좋아요",
    viewLikes = "즐겨찾기 보기",
    months = listOf("1월", "2월", "3월", "4월", "5월", "6월", "7월", "8월", "9월", "10월", "11월", "12월"),
    smartOrganizeTitle = "스마트 정리",
    noClustersFound = "제안 없음",
    moveTo = "이동",
    move = "이동",
    collapse = "접기",
    viewAll = "모두 보기",
    monthly = "월별 정리",
    monthlyTitle = "월별 정리",
    monthlyDoneTitle = "이번 달 정리 완료!",
    monthlyDoneButton = "월별로 돌아가기",
    selectLanguage = "언어 선택",
    back = "뒤로",
    privacyTitle = "개인정보 처리방침",
    privacyButton = "개인정보",
    privacySection1Title = "데이터 수집",
    privacySection1Content = "사진 정리를 위해서만 사진과 동영상에 접근합니다. 저장소 권한은 이 목적으로만 필요합니다. 개인 정보는 수집하지 않습니다.",
    privacySection2Title = "개인정보 보호",
    privacySection2Content = "오프라인으로 작동합니다. 인터넷 연결이나 로그인이 필요 없으며, 사용자 행동을 추적하거나 분석하지 않습니다.",
    privacySection3Title = "데이터 안전",
    privacySection3Content = "데이터는 기기에만 저장됩니다. 모든 처리는 로컬에서 이루어지며, 사진은 휴대폰을 벗어나지 않습니다.",
    privacySection4Title = "오픈 소스 및 감사 가능",
    privacySection4Content = "photoo는 '소스 공개' 소프트웨어입니다. 코드를 검토하여 개인정보 보호 약속을 확인할 수 있습니다. 투명성을 위해 최선을 다하고 있습니다.",
    onboardingWelcomeTitle = "photoo에 오신 것을 환영합니다",
    onboardingWelcomeSubtitle = "몇 분 만에 정리하고 압축하세요.",
    onboardingNext = "다음",
    onboardingBack = "이전",
    onboardingLanguageTitle = "언어 선택",
    onboardingLanguageSubtitle = "기기 언어가 기본입니다. 언제든 변경할 수 있습니다.",
    onboardingPermissionTitle = "미디어 접근",
    onboardingPermissionSubtitle = "정리와 압축을 위해 사진과 동영상 접근이 필요합니다.",
    onboardingPermissionButton = "권한 허용",
    onboardingPermissionGranted = "권한 허용됨",
    onboardingStartTitle = "준비 완료",
    onboardingStartSubtitle = "photoo를 시작할 준비가 되었습니다.",
    onboardingStartButton = "시작",
    batchSize = "배치 크기",
    queueOrder = "대기열 순서",
    orderRandom = "랜덤",
    orderTime = "시간",
    releaseKept = "처리된 사진 해제",
    releaseKeptDesc = "처리된 사진을 대기열로 되돌립니다",
    released = "해제됨",
    version = "버전",
    copyright = "©superwatermelon",
    releaseDialogTitle = "사진 해제?",
    releaseDialogContent = "처리된 모든 사진이 대기열로 되돌아갑니다. 계속하시겠습니까?",
    confirm = "확인",
    muteVideos = "비디오 및 라이브 포토 음소거",
    soundEffects = "음향 효과",
    haptics = "햅틱 피드백",
    comboAnimation = "콤보 애니메이션",
    filterTitle = "필터",
    filterType = "미디어 유형",
    filterFolder = "폴더",
    apply = "적용",
    filterAll = "전체",
    filterImage = "이미지",
    filterVideo = "비디오",
    filterLive = "라이브",
    viewTrash = "삭제 대기열 보기",
    lowQuality = "저화질",
    blur = "흐림",
    underexposed = "노출 부족",
    overexposed = "노출 과다",
    closedEyes = "눈 감음",
    smallFile = "작은 파일",
    lowResolution = "저해상도",
    scanLowQuality = "저화질 스캔",
    noLowQualityFound = "저화질 사진을 찾을 수 없습니다",
    lowQualityDone = "모든 저화질 사진이 처리되었습니다!",
    solidColor = "단색",
    deepOrganizeTitle = "심층 정리",
    deepOrganizeScanning = "갤러리 스캔 중...",
    deepOrganizeComplete = "스캔 완료",
    deepOrganizeScanningDesc = "품질, 유사성 및 이벤트를 분석 중입니다.",
    scanningWait = "잠시만 기다려 주세요...",
    scanningDescriptionDetailed = "갤러리 크기에 따라 약 %d분이 소요될 수 있습니다. 종료하고 백그라운드에서 실행되도록 할 수 있습니다.",
    exit = "종료",
    similarPhotosSubtitle = "중복 사진 찾기 및 정리",
    smartOrganizeSubtitle = "이벤트 및 위치별로 사진 그룹화",
    lowQualitySubtitle = "흐릿하거나 어둡거나 나쁜 사진",
    videoCompressTitle = "동영상 압축",
    videoCompressSubtitle = "화질 손실을 최소화하며 용량 축소",
    videoCompressWarningTitle = "화질 안내",
    videoCompressWarningBody = "압축 시 선명도와 비트레이트가 조금 낮아질 수 있지만 대부분의 영상은 휴대폰에서 충분히 괜찮게 보입니다. 먼저 몇 개만 시험해 보고 만족하면 일괄 처리하세요.",
    videoCompressTargetLabel = "목표 비트레이트",
    videoCompressBitrateLow = "더 작은 용량",
    videoCompressBitrateBalanced = "균형",
    videoCompressBitrateHigh = "더 선명함",
    videoCompressEstimate = "예상",
    videoCompressTimes = "압축 %d회",
    videoCompressResultTitle = "압축 완료",
    videoCompressResultSaved = "절약된 용량",
    videoCompressResultCount = "압축된 비디오",
    videoCompressDeleteOriginal = "원본 삭제",
    videoCompressKeepOriginal = "원본 유지",
    videoCompressDeleteConfirmTitle = "원본 비디오를 삭제할까요?",
    videoCompressDeleteConfirmBody = "압축본이 저장되었습니다. 삭제 후에는 복구할 수 없습니다.",
    videoCompressBefore = "원본",
    videoCompressAfter = "압축 후",
    videoCompressRatio = "압축 비율",
    videoCompressAction = "압축 시작",
    videoCompressing = "압축 중",
    videoCompressSelectHint = "압축할 동영상을 선택하세요",
    videoCompressError = "압축 실패",
    imageCompressTitle = "사진 압축",
    imageCompressSubtitle = "사진을 압축해 공간 절약",
    imageCompressWarningTitle = "화질 안내",
    imageCompressWarningBody = "압축 시 화질이 낮아질 수 있습니다. 몇 장 먼저 테스트하세요.",
    imageCompressThresholdLabel = "필터 기준",
    videoCompressThresholdLabel = "필터 기준",
    imageCompressResultTitle = "압축 완료",
    imageCompressResultSaved = "절약된 공간",
    imageCompressResultCount = "압축된 사진",
    imageCompressDeleteOriginal = "원본 삭제",
    imageCompressKeepOriginal = "원본 유지",
    imageCompressBefore = "원본",
    imageCompressAfter = "압축 후",
    imageCompressRatio = "압축 비율",
    imageCompressAction = "압축 시작",
    imageCompressing = "압축 중",
    imageCompressSelectHint = "압축할 사진을 선택하세요",
    imageCompressError = "압축 실패",
    imageCompressOriginalLabel = "원본",
    imageCompressOriginalSize = "크기 유지",
    imageCompressSelectAll = "이 달 모두 선택",
    imageCompressSelected = "모두 선택됨",
    commentPlaceholder = "댓글 추가...",
    commentsHeader = "댓글",
    commentUser = "나",
    noLikes = "아직 좋아요가 없습니다",
    removeLikeTitle = "좋아요에서 제거",
    removeLikeMessage = "이 항목을 좋아요에서 제거하시겠습니까?",
    remove = "제거",
    send = "전송",
    share = "공유",
    comment = "댓글",
    removeLike = "좋아요 제거",
    avatar = "아바타",
    avatarBoy = "소년",
    avatarGirl = "소녀",
    commentUserMe = "나",
    deleteCommentTitle = "댓글 삭제?",
    deleteCommentMessage = "이 댓글을 삭제하시겠습니까?",
    copyComment = "복사",
    commentCopied = "댓글이 복사되었습니다",
    holidayNewYear = "새해",
    holidayValentines = "발렌타인 데이",
    holidayChildrens = "어린이날",
    holidayLaborDay = "노동절",
    holidayNationalDay = "국경절",
    holidaySpringFestival = "설날",
    holidayDragonBoat = "단오",
    holidayMidAutumn = "추석",
    groupPhotosTitle = "단체 사진",
    filterCompletedTitle = "필터 완료",
    filterCompletedSubtitle = "%1\$s의 모든 항목을 검토했습니다.",
    reviewAgain = "다시 검토 (모두 해제)",
    changeFilter = "필터 변경",
    selectMonth = "월 선택",
    filterMonth = "월",
    shootingStatsTitle = "앨범 인사이트",
    shootingStatsYear = "년",
    shootingStatsMonth = "월",
    shootingStatsSummary = "%1\$s에 %2\$s개의 순간을 기록했습니다.",
    shootingStatsSummaryMonth = "%1\$s에 %2\$s개의 순간을 기록했습니다.",
    shootingStatsItems = "%1\$s 사진 | %2\$s 동영상",
    shootingStatsVideoDuration = "총 동영상 시간: %1\$s분",
    shootingStatsMovies = "영화 %1\$s편 분량",
    shootingStatsShortDrama = "짧은 드라마 %1\$s화 분량",
    shootingStatsTvDrama = "드라마 %1\$s화 분량",
    shootingStatsScreenshots = "스크린샷",
    shootingStatsSelfies = "셀카",
    shootingStatsMostActiveDay = "가장 활발한 날: %1\$s (%2\$s개 항목)",
    shootingStatsVideoTitle = "동영상",
    shootingStatsActiveDayTitle = "활동적인 날",
    shootingStatsLocationTitle = "위치",
    shootingStatsLocationPlaces = "%1\$s 장소",
    shootingStatsHeatmapTitle = "활동 히트맵",
    shootingStatsHeatmapLess = "적음",
    shootingStatsHeatmapMore = "많음",
    newFolder = "새 폴더",
    createNewFolder = "새 폴더 만들기",
    folderName = "폴더 이름",
    create = "만들기",
    undoSuccess = "취소됨",
    readyForNextBatch = "다음 배치를 준비하시겠습니까? (%1\$d개 항목 남음)",
    continueOrganizing = "더 정리하기",
    privacyPolicy = "개인정보 처리방침",
    termsOfService = "이용약관",
    agreeToTerms = "이용약관 및 개인정보 처리방침에 동의합니다",
    manageFilesPermission = "모든 파일 관리",
    manageFilesPermissionDesc = "사진을 폴더로 이동하고 갤러리 구조를 정리하기 위해 필요합니다.",
    currentFolder = "현재 폴더",
    openSourceLicenses = "오픈 소스 라이선스"
)

val StringsJa = LocalizedStrings(
    undo = "元に戻す",
    clean = "クリーン",
    stats = "統計",
    skip = "保持", // Changed from "保存" to "保持" (Keep)
    trash = "削除",
    live = "ライブ",
    unknownLocation = "不明な場所",
    camera = "カメラ",
    location = "場所",
    iso = "ISO",
    shutter = "シャッター",
    date = "日付",
    size = "サイズ",
    resolution = "解像度",
    filename = "ファイル名",
    settings = "設定",
    language = "言語",
    processed = "処理済み",
    deleted = "削除済み",
    skippedLabel = "スキップ",
    savedSpace = "節約容量",
    emptyStateTitle = "完了！",
    emptyStateSubtitle = "このバッチのメディアを整理しました。",
    emptyStateButton = "もっと読み込む",
    permissionsNeed = "メディアへのアクセス権限が必要です",
    timeSaved = "節約時間",
    totalProcessed = "処理済み総数",
    ofGallery = "ギャラリーの割合",
    savedSpaceRatioFormat = "%1\$s%% (合計 %2\$sGB)",
    pressAgainToExit = "もう一度押すと終了します",
    deleteReviewTitle = "削除の確認",
    deleteReviewSubtitle = "削除する項目を選択してください。選択されていない項目は保持されます。",
    cancel = "キャンセル",
    delete = "削除",
    similar = "類似",
    noSimilarPhotosFound = "類似の写真は見つかりませんでした",
    scanning = "スキャン中...",
    stop = "停止",
    keepSelected = "選択を保持",
    keepAll = "すべて保持",
    deleteAll = "すべて削除",
    selectBest = "保持する最適な写真を選択してください。",
    similarPhotosDone = "すべての類似写真が処理されました！",
    done = "完了",
    noSimilarPhotos = "類似の写真は見つかりませんでした",
    likes = "いいね",
    viewLikes = "お気に入りを表示",
    months = listOf("1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"),
    smartOrganizeTitle = "スマート整理",
    noClustersFound = "提案はありません",
    moveTo = "移動",
    move = "移動",
    collapse = "折りたたむ",
    viewAll = "すべて表示",
    monthly = "月別整理",
    monthlyTitle = "月別整理",
    monthlyDoneTitle = "今月は完了しました！",
    monthlyDoneButton = "月別に戻る",
    selectLanguage = "言語を選択",
    back = "戻る",
    privacyTitle = "プライバシーポリシー",
    privacyButton = "プライバシー",
    privacySection1Title = "データ収集",
    privacySection1Content = "写真の整理を支援するためにのみ、写真と動画にアクセスします。この目的のためにのみストレージ権限が必要です。個人情報は収集しません。",
    privacySection2Title = "プライバシー保護",
    privacySection2Content = "オフラインで動作します。インターネット接続やログインは不要で、ユーザーの行動追跡やユーザー分析は行いません。",
    privacySection3Title = "データの安全性",
    privacySection3Content = "データはデバイス上にのみ保存されます。すべての処理はローカルで行われ、写真が携帯電話から外部に出ることはありません。",
    privacySection4Title = "オープンソースと監査可能",
    privacySection4Content = "photooは「ソース公開」ソフトウェアです。コードを確認して、プライバシーの取り組みを検証できます。透明性に尽力しています。",
    onboardingWelcomeTitle = "photooへようこそ",
    onboardingWelcomeSubtitle = "数分で整理と圧縮ができます。",
    onboardingNext = "次へ",
    onboardingBack = "戻る",
    onboardingLanguageTitle = "言語を選択",
    onboardingLanguageSubtitle = "端末の言語が既定です。いつでも変更できます。",
    onboardingPermissionTitle = "メディアへのアクセス",
    onboardingPermissionSubtitle = "整理と圧縮のために写真と動画へのアクセスが必要です。",
    onboardingPermissionButton = "許可する",
    onboardingPermissionGranted = "許可済み",
    onboardingStartTitle = "準備完了",
    onboardingStartSubtitle = "photooを始めましょう。",
    onboardingStartButton = "開始",
    batchSize = "バッチサイズ",
    queueOrder = "キュー順序",
    orderRandom = "ランダム",
    orderTime = "時間",
    releaseKept = "処理済みの写真を解放",
    releaseKeptDesc = "処理済みの写真をキューに戻します",
    released = "解放済み",
    filterCompletedTitle = "フィルタ完了",
    filterCompletedSubtitle = "このフィルタのすべての項目（%1\$s）を確認しました。",
    reviewAgain = "再確認（すべて解放）",
    changeFilter = "フィルタ変更",
    selectMonth = "月を選択",
    filterMonth = "月",
    version = "バージョン",
    copyright = "©superwatermelon",
    releaseDialogTitle = "写真を解放しますか？",
    releaseDialogContent = "処理されたすべての写真がキューに戻されます。よろしいですか？",
    confirm = "確認",
    muteVideos = "ビデオとLive Photosをミュート",
    soundEffects = "効果音",
    haptics = "触覚フィードバック",
    comboAnimation = "コンボ演出",
    filterTitle = "フィルター",
    filterType = "メディアタイプ",
    filterFolder = "フォルダ",
    apply = "適用",
    filterAll = "すべて",
    filterImage = "画像",
    filterVideo = "動画",
    filterLive = "ライブ",
    viewTrash = "削除キューを表示",
    lowQuality = "低品質",
    blur = "ぼやけている",
    underexposed = "露出不足",
    overexposed = "露出オーバー",
    closedEyes = "目つぶり",
    smallFile = "小さいファイル",
    lowResolution = "低解像度",
    scanLowQuality = "低品質スキャン",
    noLowQualityFound = "低品質の写真は見つかりませんでした",
    lowQualityDone = "すべての低品質写真が処理されました！",
    solidColor = "単色",
    deepOrganizeTitle = "詳細整理",
    deepOrganizeScanning = "ギャラリーをスキャン中...",
    deepOrganizeComplete = "スキャン完了",
    deepOrganizeScanningDesc = "品質、類似性、イベントを分析しています。",
    scanningWait = "お待ちください...",
    scanningDescriptionDetailed = "ギャラリーのサイズによっては、約%d分かかる場合があります。終了してバックグラウンドで実行させることができます。",
    exit = "終了",
    similarPhotosSubtitle = "重複した写真を見つけて整理",
    smartOrganizeSubtitle = "イベントと場所で写真をグループ化",
    lowQualitySubtitle = "ぼやけた、暗い、悪い写真",
    videoCompressTitle = "動画圧縮",
    videoCompressSubtitle = "画質低下を抑えつつ容量削減",
    videoCompressWarningTitle = "画質の注意",
    videoCompressWarningBody = "圧縮で画質やビットレートが少し下がることがありますが、多くの動画はスマホで十分きれいに見えます。まず数本試して、問題なければまとめて圧縮してください。",
    videoCompressTargetLabel = "目標ビットレート",
    videoCompressBitrateLow = "小さめ",
    videoCompressBitrateBalanced = "バランス",
    videoCompressBitrateHigh = "高画質",
    videoCompressEstimate = "推定",
    videoCompressTimes = "圧縮 %d回",
    videoCompressResultTitle = "圧縮完了",
    videoCompressResultSaved = "節約できた容量",
    videoCompressResultCount = "圧縮済み動画",
    videoCompressDeleteOriginal = "元の動画を削除",
    videoCompressKeepOriginal = "元の動画を保持",
    videoCompressDeleteConfirmTitle = "元の動画を削除しますか？",
    videoCompressDeleteConfirmBody = "圧縮済みの動画は保存されています。削除後は元に戻せません。",
    videoCompressBefore = "元のサイズ",
    videoCompressAfter = "圧縮後",
    videoCompressRatio = "圧縮率",
    videoCompressAction = "圧縮開始",
    videoCompressing = "圧縮中",
    videoCompressSelectHint = "圧縮する動画を選択してください",
    videoCompressError = "圧縮に失敗しました",
    imageCompressTitle = "写真圧縮",
    imageCompressSubtitle = "写真を圧縮して容量節約",
    imageCompressWarningTitle = "画質の注意",
    imageCompressWarningBody = "圧縮で画質が低下します。まず少量で試してください。",
    imageCompressThresholdLabel = "表示しきい値",
    videoCompressThresholdLabel = "表示しきい値",
    imageCompressResultTitle = "圧縮完了",
    imageCompressResultSaved = "節約容量",
    imageCompressResultCount = "圧縮した写真",
    imageCompressDeleteOriginal = "元画像を削除",
    imageCompressKeepOriginal = "元画像を保持",
    imageCompressBefore = "元サイズ",
    imageCompressAfter = "圧縮後",
    imageCompressRatio = "圧縮率",
    imageCompressAction = "圧縮開始",
    imageCompressing = "圧縮中",
    imageCompressSelectHint = "圧縮する写真を選択",
    imageCompressError = "圧縮に失敗しました",
    imageCompressOriginalLabel = "原寸",
    imageCompressOriginalSize = "サイズ維持",
    imageCompressSelectAll = "今月を全選択",
    imageCompressSelected = "全選択済み",
    commentPlaceholder = "コメントを追加...",
    commentsHeader = "コメント",
    commentUser = "あなた",
    noLikes = "まだいいねはありません",
    removeLikeTitle = "いいねから削除",
    removeLikeMessage = "このアイテムをいいねから削除してもよろしいですか？",
    remove = "削除",
    send = "送信",
    share = "共有",
    comment = "コメント",
    removeLike = "いいねを削除",
    avatar = "アバター",
    avatarBoy = "男の子",
    avatarGirl = "女の子",
    commentUserMe = "私",
    deleteCommentTitle = "コメントを削除？",
    deleteCommentMessage = "このコメントを削除してもよろしいですか？",
    copyComment = "コピー",
    commentCopied = "コメントをコピーしました",
    holidayNewYear = "元日",
    holidayValentines = "バレンタインデー",
    holidayChildrens = "こどもの日",
    holidayLaborDay = "メーデー",
    holidayNationalDay = "建国記念の日",
    holidaySpringFestival = "春節",
    holidayDragonBoat = "端午の節句",
    holidayMidAutumn = "中秋節",
    groupPhotosTitle = "グループ写真",
    shootingStatsTitle = "アルバムインサイト",
    shootingStatsYear = "年",
    shootingStatsMonth = "月",
    shootingStatsSummary = "%1\$sに%2\$s個の瞬間を記録しました。",
    shootingStatsSummaryMonth = "%1\$sに%2\$s個の瞬間を記録しました。",
    shootingStatsItems = "%1\$s 写真 | %2\$s 動画",
    shootingStatsVideoDuration = "動画合計: %1\$s分",
    shootingStatsMovies = "映画%1\$s本分に相当",
    shootingStatsShortDrama = "短編ドラマ%1\$s本分に相当",
    shootingStatsTvDrama = "ドラマ%1\$s話分に相当",
    shootingStatsScreenshots = "スクリーンショット",
    shootingStatsSelfies = "セルフィー",
    shootingStatsMostActiveDay = "最もアクティブな日: %1\$s (%2\$s項目)",
    shootingStatsVideoTitle = "動画",
    shootingStatsActiveDayTitle = "アクティブな日",
    shootingStatsLocationTitle = "場所",
    shootingStatsLocationPlaces = "%1\$s 箇所",
    shootingStatsHeatmapTitle = "アクティビティのヒートマップ",
    shootingStatsHeatmapLess = "少",
    shootingStatsHeatmapMore = "多",
    newFolder = "New Folder",
    createNewFolder = "Create New Folder",
    folderName = "Folder Name",
    create = "Create",
    undoSuccess = "Undone",
    readyForNextBatch = "次のバッチの準備はできましたか？（残り %1\$d 項目）",
    continueOrganizing = "整理を続ける",
    privacyPolicy = "プライバシーポリシー",
    termsOfService = "利用規約",
    agreeToTerms = "利用規約とプライバシーポリシーに同意します",
    manageFilesPermission = "すべてのファイルを管理",
    manageFilesPermissionDesc = "写真をフォルダに移動し、ギャラリーの構造を整理するために必要です。",
    currentFolder = "現在のフォルダ",
    openSourceLicenses = "オープンソースライセンス"
)

val StringsFr = LocalizedStrings(
    undo = "Annuler",
    clean = "Nettoyer",
    stats = "Stats",
    skip = "GARDER",
    trash = "SUPPR",
    live = "LIVE",
    unknownLocation = "Lieu inconnu",
    camera = "CAMÉRA",
    location = "LIEU",
    iso = "ISO",
    shutter = "OBTURATEUR",
    date = "DATE",
    size = "TAILLE",
    resolution = "RÉSOLUTION",
    filename = "NOM DE FICHIER",
    settings = "Paramètres",
    language = "Langue",
    processed = "Traités",
    deleted = "Supprimés",
    skippedLabel = "Ignorés",
    savedSpace = "Espace libéré",
    emptyStateTitle = "Tout est bon !",
    emptyStateSubtitle = "Vous avez trié ce lot de médias.",
    emptyStateButton = "Charger plus",
    permissionsNeed = "Besoin de permissions pour accéder aux médias",
    timeSaved = "Temps gagné",
    totalProcessed = "Total traité",
    ofGallery = "de la galerie",
    savedSpaceRatioFormat = "%1\$s%% (Total %2\$sGB)",
    pressAgainToExit = "Appuyez à nouveau pour quitter",
    deleteReviewTitle = "Confirmer la suppression",
    deleteReviewSubtitle = "Sélectionnez les éléments à supprimer. Les éléments non sélectionnés seront conservés.",
    cancel = "Annuler",
    delete = "Supprimer",
    similar = "Similaire",
    noSimilarPhotosFound = "Aucune photo similaire trouvée",
    scanning = "Analyse...",
    stop = "Arrêter",
    keepSelected = "Garder la sélection",
    keepAll = "Tout garder",
    deleteAll = "Tout supprimer",
    selectBest = "Sélectionnez la meilleure photo à garder.",
    similarPhotosDone = "Toutes les photos similaires ont été traitées !",
    done = "Terminé",
    noSimilarPhotos = "Aucune photo similaire trouvée",
    likes = "J'aime",
    viewLikes = "Voir les favoris",
    months = listOf("Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"),
    smartOrganizeTitle = "Organisation Intelligente",
    noClustersFound = "Aucune suggestion trouvée",
    moveTo = "Déplacer vers",
    move = "Déplacer",
    collapse = "Réduire",
    viewAll = "Voir tout",
    monthly = "Mensuel",
    monthlyTitle = "Organisation mensuelle",
    monthlyDoneTitle = "Mois terminé !",
    monthlyDoneButton = "Retour aux mois",
    selectLanguage = "Choisir la langue",
    back = "Retour",
    privacyTitle = "Politique de confidentialité",
    privacyButton = "Confidentialité",
    privacySection1Title = "Collecte de données",
    privacySection1Content = "Nous accédons uniquement à vos photos et vidéos pour vous aider à les organiser. Les permissions de stockage ne sont requises que pour cela. Nous ne collectons aucune information personnelle.",
    privacySection2Title = "Protection de la vie privée",
    privacySection2Content = "Nous fonctionnons hors ligne. Aucune connexion internet ni connexion compte n'est requise. Nous ne suivons pas vos actions ni n'effectuons d'analyse utilisateur.",
    privacySection3Title = "Sécurité des données",
    privacySection3Content = "Vos données restent sur votre appareil. Tout le traitement est local, vos photos ne quittent jamais votre téléphone.",
    privacySection4Title = "Open Source & Auditable",
    privacySection4Content = "photoo est un logiciel 'Source Available'. Vous pouvez examiner le code pour vérifier nos engagements de confidentialité. Nous nous engageons à la transparence.",
    onboardingWelcomeTitle = "Bienvenue sur photoo",
    onboardingWelcomeSubtitle = "Organisez et compressez vos souvenirs en quelques minutes.",
    onboardingNext = "Suivant",
    onboardingBack = "Retour",
    onboardingLanguageTitle = "Choisir la langue",
    onboardingLanguageSubtitle = "La langue de l’appareil est sélectionnée par défaut. Modifiable à tout moment.",
    onboardingPermissionTitle = "Accès aux médias",
    onboardingPermissionSubtitle = "Nous avons besoin d’accéder à vos photos et vidéos pour organiser et compresser.",
    onboardingPermissionButton = "Autoriser",
    onboardingPermissionGranted = "Autorisation accordée",
    onboardingStartTitle = "Tout est prêt",
    onboardingStartSubtitle = "Vous pouvez commencer à utiliser photoo.",
    onboardingStartButton = "Commencer",
    batchSize = "Taille du lot",
    queueOrder = "Ordre de la file",
    orderRandom = "Aléatoire",
    orderTime = "Temps",
    releaseKept = "Libérer les photos traitées",
    releaseKeptDesc = "Remettre les photos traitées dans la file",
    released = "Libéré",
    filterCompletedTitle = "Filtre terminé",
    filterCompletedSubtitle = "Vous avez passé en revue tous les éléments de %1\$s.",
    reviewAgain = "Revoir (Tout libérer)",
    changeFilter = "Changer de filtre",
    selectMonth = "Choisir le mois",
    filterMonth = "Mois",
    version = "Version",
    copyright = "©superwatermelon",
    releaseDialogTitle = "Libérer les photos ?",
    releaseDialogContent = "Cela remettra toutes les photos traitées dans la file d'attente. Êtes-vous sûr ?",
    confirm = "Confirmer",
    muteVideos = "Couper le son des vidéos et Live Photos",
    filterTitle = "Filtrer",
    filterType = "Type de média",
    filterFolder = "Dossier",
    apply = "Appliquer",
    filterAll = "Tout",
    filterImage = "Image",
    filterVideo = "Vidéo",
    filterLive = "Live",
    viewTrash = "Voir la file de suppression",
    lowQuality = "Basse Qualité",
    blur = "Flou",
    underexposed = "Sous-exposé",
    overexposed = "Surexposé",
    closedEyes = "Yeux fermés",
    smallFile = "Petit fichier",
    lowResolution = "Basse résolution",
    scanLowQuality = "Scanner Basse Qualité",
    noLowQualityFound = "Aucune photo de basse qualité trouvée",
    lowQualityDone = "Toutes les photos de basse qualité ont été traitées !",
    solidColor = "Couleur unie",
    deepOrganizeTitle = "Organisation approfondie",
    deepOrganizeScanning = "Analyse de la galerie...",
    deepOrganizeComplete = "Analyse terminée",
    deepOrganizeScanningDesc = "Analyse de la qualité, de la similarité et des événements.",
    scanningWait = "Veuillez patienter...",
    scanningDescriptionDetailed = "Cela peut prendre environ %d minutes selon la taille de votre galerie. Vous pouvez quitter et laisser l'analyse s'exécuter en arrière-plan.",
    exit = "Quitter",
    similarPhotosSubtitle = "Trouver et nettoyer les doublons",
    smartOrganizeSubtitle = "Grouper par événements et lieux",
    lowQualitySubtitle = "Photos floues, sombres et mauvaises",
    videoCompressTitle = "Compression vidéo",
    videoCompressSubtitle = "Réduire la taille avec peu de perte de qualité",
    videoCompressWarningTitle = "Avertissement qualité",
    videoCompressWarningBody = "La compression peut légèrement réduire la netteté et le débit, mais la plupart des vidéos restent agréables sur mobile. Testez quelques vidéos, puis compressez en lot si le résultat vous convient.",
    videoCompressTargetLabel = "Débit cible",
    videoCompressBitrateLow = "Plus petit",
    videoCompressBitrateBalanced = "Équilibré",
    videoCompressBitrateHigh = "Plus net",
    videoCompressEstimate = "Estimation",
    videoCompressTimes = "Compressé %d fois",
    videoCompressResultTitle = "Compression terminée",
    videoCompressResultSaved = "Espace économisé",
    videoCompressResultCount = "Vidéos compressées",
    videoCompressDeleteOriginal = "Supprimer les originaux",
    videoCompressKeepOriginal = "Conserver les originaux",
    videoCompressDeleteConfirmTitle = "Supprimer les vidéos originales ?",
    videoCompressDeleteConfirmBody = "Les versions compressées sont enregistrées. Cette suppression est définitive.",
    videoCompressBefore = "Original",
    videoCompressAfter = "Compressé",
    videoCompressRatio = "Taux de compression",
    videoCompressAction = "Démarrer la compression",
    videoCompressing = "Compression en cours",
    videoCompressSelectHint = "Sélectionnez des vidéos à compresser",
    videoCompressError = "Échec de la compression",
    imageCompressTitle = "Compression d'images",
    imageCompressSubtitle = "Compresser les photos pour libérer de l'espace",
    imageCompressWarningTitle = "Avertissement qualité",
    imageCompressWarningBody = "La compression réduit la qualité. Essayez d'abord quelques images.",
    imageCompressThresholdLabel = "Seuil de filtre",
    videoCompressThresholdLabel = "Seuil de filtre",
    imageCompressResultTitle = "Compression terminée",
    imageCompressResultSaved = "Espace économisé",
    imageCompressResultCount = "Photos compressées",
    imageCompressDeleteOriginal = "Supprimer les originales",
    imageCompressKeepOriginal = "Conserver les originales",
    imageCompressBefore = "Avant",
    imageCompressAfter = "Après",
    imageCompressRatio = "Taux de compression",
    imageCompressAction = "Démarrer la compression",
    imageCompressing = "Compression en cours",
    imageCompressSelectHint = "Sélectionnez des photos à compresser",
    imageCompressError = "Échec de la compression",
    imageCompressOriginalLabel = "ORIGINAL",
    imageCompressOriginalSize = "Conserver la taille",
    imageCompressSelectAll = "Tout sélectionner",
    imageCompressSelected = "Tout sélectionné",
    commentPlaceholder = "Ajouter un commentaire...",
    commentsHeader = "commentaires",
    commentUser = "Vous",
    noLikes = "Pas encore de j'aime",
    removeLikeTitle = "Retirer des J'aime",
    removeLikeMessage = "Voulez-vous vraiment retirer cet élément de vos J'aime ?",
    remove = "Retirer",
    send = "Envoyer",
    share = "Partager",
    comment = "Commentaire",
    removeLike = "Retirer J'aime",
    avatar = "Avatar",
    avatarBoy = "Garçon",
    avatarGirl = "Fille",
    commentUserMe = "Moi",
    deleteCommentTitle = "Supprimer le commentaire ?",
    deleteCommentMessage = "Êtes-vous sûr de vouloir supprimer ce commentaire ?",
    copyComment = "Copier",
    commentCopied = "Commentaire copié",
    holidayNewYear = "Jour de l'An",
    holidayValentines = "Saint-Valentin",
    holidayChildrens = "Journée des enfants",
    holidayLaborDay = "Fête du Travail",
    holidayNationalDay = "Fête Nationale",
    holidaySpringFestival = "Nouvel An Chinois",
    holidayDragonBoat = "Fête des Bateaux-Dragons",
    holidayMidAutumn = "Fête de la Mi-Automne",
    groupPhotosTitle = "Photos de groupe",
    shootingStatsTitle = "Aperçus d’album",
    shootingStatsYear = "Année",
    shootingStatsMonth = "Mois",
    shootingStatsSummary = "En %1\$s, vous avez enregistré %2\$s moments.",
    shootingStatsSummaryMonth = "En %1\$s, vous avez enregistré %2\$s moments.",
    shootingStatsItems = "%1\$s Photos | %2\$s Vidéos",
    shootingStatsVideoDuration = "Total Vidéo : %1\$s min",
    shootingStatsMovies = "Équivaut à regarder %1\$s films",
    shootingStatsShortDrama = "Équivaut à %1\$s mini‑séries",
    shootingStatsTvDrama = "Équivaut à %1\$s épisodes de série",
    shootingStatsScreenshots = "Captures d'écran",
    shootingStatsSelfies = "Selfies",
    shootingStatsMostActiveDay = "Jour le plus actif : %1\$s (%2\$s éléments)",
    shootingStatsVideoTitle = "Vidéo",
    shootingStatsActiveDayTitle = "Jour actif",
    shootingStatsLocationTitle = "Lieu",
    shootingStatsLocationPlaces = "%1\$s Lieux",
    shootingStatsHeatmapTitle = "Carte de chaleur d'activité",
    shootingStatsHeatmapLess = "Moins",
    shootingStatsHeatmapMore = "Plus",
    soundEffects = "Effets sonores",
    haptics = "Retour haptique",
    comboAnimation = "Animation combo",
    newFolder = "Nouveau dossier",
    createNewFolder = "Créer un nouveau dossier",
    folderName = "Nom du dossier",
    create = "Créer",
    undoSuccess = "Annulé",
    readyForNextBatch = "Prêt pour le prochain lot ? (%1\$d éléments restants)",
    continueOrganizing = "Continuer l'organisation",
    privacyPolicy = "Politique de confidentialité",
    termsOfService = "Conditions d'utilisation",
    agreeToTerms = "J'accepte les conditions d'utilisation et la politique de confidentialité",
    manageFilesPermission = "Gérer tous les fichiers",
    manageFilesPermissionDesc = "Nécessaire pour déplacer les photos dans des dossiers et organiser la structure de votre galerie.",
    currentFolder = "Dossier actuel",
    openSourceLicenses = "Licences Open Source"
)

val StringsAr = LocalizedStrings(
    undo = "تراجع",
    clean = "تنظيف",
    stats = "إحصائيات",
    skip = "إبقاء", // Changed from "حفظ" to "إبقاء" (Keep)
    trash = "حذف",
    live = "حي",
    unknownLocation = "موقع غير معروف",
    camera = "كاميرا",
    location = "موقع",
    iso = "ISO",
    shutter = "الغالق",
    date = "تاريخ",
    size = "حجم",
    resolution = "دقة",
    filename = "اسم الملف",
    settings = "إعدادات",
    language = "لغة",
    processed = "معالج",
    deleted = "محذوف",
    skippedLabel = "تم التخطي",
    savedSpace = "مساحة موفرة",
    emptyStateTitle = "انتهيت!",
    emptyStateSubtitle = "لقد قمت بتنظيم هذه الدفعة من الوسائط.",
    emptyStateButton = "تحميل المزيد",
    permissionsNeed = "بحاجة إلى أذونات للوصول إلى الوسائط",
    timeSaved = "الوقت الموفر",
    totalProcessed = "إجمالي المعالجة",
    ofGallery = "من المعرض",
    savedSpaceRatioFormat = "%1\$s%% (مجموع %2\$sGB)",
    pressAgainToExit = "اضغط مرة أخرى للخروج",
    deleteReviewTitle = "مراجعة الحذف",
    deleteReviewSubtitle = "حدد العناصر المراد حذفها. سيتم الاحتفاظ بالعناصر غير المحددة.",
    cancel = "إلغاء",
    delete = "حذف",
    similar = "مماثل",
    noSimilarPhotosFound = "لم يتم العثور على صور مماثلة",
    scanning = "جاري المسح...",
    stop = "توقف",
    keepSelected = "الاحتفاظ بالمحدد",
    keepAll = "الاحتفاظ بالكل",
    deleteAll = "حذف الكل",
    selectBest = "حدد الأفضل للاحتفاظ به.",
    similarPhotosDone = "تمت معالجة جميع الصور المتشابهة!",
    done = "تم",
    noSimilarPhotos = "لم يتم العثور على صور مماثلة",
    likes = "إعجابات",
    viewLikes = "عرض المفضلة",
    months = listOf("يناير", "فبراير", "مارس", "أبريل", "مايو", "يونيو", "يوليو", "أغسطس", "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر"),
    smartOrganizeTitle = "تنظيم ذكي",
    noClustersFound = "لا توجد اقتراحات",
    moveTo = "نقل إلى",
    move = "نقل",
    collapse = "طي",
    viewAll = "عرض الكل",
    monthly = "شهري",
    monthlyTitle = "تنظيم شهري",
    monthlyDoneTitle = "اكتمل هذا الشهر!",
    monthlyDoneButton = "العودة إلى الأشهر",
    selectLanguage = "اختر اللغة",
    back = "رجوع",
    privacyTitle = "سياسة الخصوصية",
    privacyButton = "الخصوصية",
    privacySection1Title = "جمع البيانات",
    privacySection1Content = "نحن نصل فقط إلى صورك ومقاطع الفيديو لمساعدتك في تنظيمها. نطلب إذن التخزين لهذا الغرض فقط. نحن لا نجمع أي معلومات شخصية.",
    privacySection2Title = "حماية الخصوصية",
    privacySection2Content = "نحن نعمل دون اتصال بالإنترنت. لا يلزم الاتصال بالإنترنت أو تسجيل الدخول، ولا نتتبع سلوك المستخدم أو نجري تحليلات للمستخدم.",
    privacySection3Title = "أمان البيانات",
    privacySection3Content = "بياناتك تبقى على جهازك. تتم جميع المعالجات محليًا، مما يضمن عدم مغادرة صورك لهاتفك.",
    privacySection4Title = "مفتوح المصدر وقابل للمراجعة",
    privacySection4Content = "photoo هو برنامج 'متاح المصدر'. يمكنك مراجعة الكود للتحقق من وعودنا بالخصوصية. نحن ملتزمون بالشفافية.",
    onboardingWelcomeTitle = "مرحبًا بك في photoo",
    onboardingWelcomeSubtitle = "نظّم واضغط ذكرياتك خلال دقائق.",
    onboardingNext = "التالي",
    onboardingBack = "السابق",
    onboardingLanguageTitle = "اختر اللغة",
    onboardingLanguageSubtitle = "لغة الجهاز هي الافتراضية ويمكن تغييرها لاحقًا.",
    onboardingPermissionTitle = "إذن الوصول للوسائط",
    onboardingPermissionSubtitle = "نحتاج الوصول إلى الصور والفيديوهات للتنظيم والضغط.",
    onboardingPermissionButton = "منح الإذن",
    onboardingPermissionGranted = "تم منح الإذن",
    onboardingStartTitle = "كل شيء جاهز",
    onboardingStartSubtitle = "يمكنك البدء باستخدام photoo.",
    onboardingStartButton = "ابدأ",
    batchSize = "حجم الدفعة",
    queueOrder = "ترتيب القائمة",
    orderRandom = "عشوائي",
    orderTime = "وقت",
    releaseKept = "إطلاق الصور المعالجة",
    releaseKeptDesc = "إعادة تعيين الصور المعالجة إلى القائمة",
    released = "تم الإطلاق",
    filterCompletedTitle = "اكتمل التصفية",
    filterCompletedSubtitle = "لقد قمت بمراجعة جميع العناصر في %1\$s.",
    reviewAgain = "مراجعة مرة أخرى (تحرير الكل)",
    changeFilter = "تغيير المرشح",
    selectMonth = "اختر الشهر",
    filterMonth = "شهر",
    version = "إصدار",
    copyright = "©superwatermelon",
    releaseDialogTitle = "إطلاق الصور؟",
    releaseDialogContent = "سيؤدي هذا إلى إعادة تعيين جميع الصور المعالجة إلى قائمة الانتظار. هل أنت متأكد؟",
    confirm = "تأكيد",
    muteVideos = "كتم صوت الفيديو والصور الحية",
    soundEffects = "تأثيرات صوتية",
    haptics = "ردود فعل لمسية",
    comboAnimation = "رسوم الكومبو",
    filterTitle = "تصفية",
    filterType = "نوع الوسائط",
    filterFolder = "مجلد",
    apply = "تطبيق",
    filterAll = "الكل",
    filterImage = "صورة",
    filterVideo = "فيديو",
    filterLive = "حي",
    viewTrash = "عرض قائمة الحذف",
    lowQuality = "جودة منخفضة",
    blur = "ضبابي",
    underexposed = "تعرض ناقص",
    overexposed = "تعرض زائد",
    closedEyes = "عيون مغلقة",
    smallFile = "ملف صغير",
    lowResolution = "دقة منخفضة",
    scanLowQuality = "مسح الجودة المنخفضة",
    noLowQualityFound = "لم يتم العثور على صور منخفضة الجودة",
    lowQualityDone = "تمت معالجة جميع الصور منخفضة الجودة!",
    solidColor = "لون واحد",
    deepOrganizeTitle = "تنظيم عميق",
    deepOrganizeScanning = "جاري مسح المعرض...",
    deepOrganizeComplete = "اكتمل المسح",
    deepOrganizeScanningDesc = "تحليل الصور للجودة والتشابه والأحداث.",
    scanningWait = "يرجى الانتظار...",
    scanningDescriptionDetailed = "قد يستغرق هذا حوالي %d دقائق حسب حجم المعرض. يمكنك الخروج وترك البرنامج يعمل في الخلفية.",
    exit = "خروج",
    similarPhotosSubtitle = "البحث عن اللقطات المكررة وتنظيفها",
    smartOrganizeSubtitle = "تجميع الصور حسب الأحداث والمواقع",
    lowQualitySubtitle = "صور ضبابية ومظلمة وسيئة",
    videoCompressTitle = "ضغط الفيديو",
    videoCompressSubtitle = "تقليل الحجم مع فقدان محدود للجودة",
    videoCompressWarningTitle = "تنبيه الجودة",
    videoCompressWarningBody = "قد يقلل الضغط قليلاً من الوضوح ومعدل البت، لكن معظم المقاطع تبقى جيدة على الهاتف والمشاركة. جرّب بضعة مقاطع أولاً ثم اضغطها دفعة واحدة إذا كانت النتيجة مناسبة.",
    videoCompressTargetLabel = "معدل بت مستهدف",
    videoCompressBitrateLow = "أصغر حجماً",
    videoCompressBitrateBalanced = "متوازن",
    videoCompressBitrateHigh = "أكثر وضوحاً",
    videoCompressEstimate = "متوقع",
    videoCompressTimes = "تم الضغط %d مرة",
    videoCompressResultTitle = "اكتمل الضغط",
    videoCompressResultSaved = "المساحة الموفرة",
    videoCompressResultCount = "مقاطع مضغوطة",
    videoCompressDeleteOriginal = "حذف الأصل",
    videoCompressKeepOriginal = "الاحتفاظ بالأصل",
    videoCompressDeleteConfirmTitle = "هل تريد حذف مقاطع الفيديو الأصلية؟",
    videoCompressDeleteConfirmBody = "تم حفظ النسخ المضغوطة. لن يمكن التراجع بعد الحذف.",
    videoCompressBefore = "الأصلي",
    videoCompressAfter = "بعد الضغط",
    videoCompressRatio = "نسبة الضغط",
    videoCompressAction = "بدء الضغط",
    videoCompressing = "جارٍ الضغط",
    videoCompressSelectHint = "حدد مقاطع فيديو للضغط",
    videoCompressError = "فشل الضغط",
    imageCompressTitle = "ضغط الصور",
    imageCompressSubtitle = "ضغط الصور لتوفير المساحة",
    imageCompressWarningTitle = "تنبيه الجودة",
    imageCompressWarningBody = "الضغط يقلل الجودة. جرّب عدداً قليلاً أولاً.",
    imageCompressThresholdLabel = "حد الفلترة",
    videoCompressThresholdLabel = "حد الفلترة",
    imageCompressResultTitle = "اكتمل الضغط",
    imageCompressResultSaved = "المساحة الموفرة",
    imageCompressResultCount = "صور مضغوطة",
    imageCompressDeleteOriginal = "حذف الأصلية",
    imageCompressKeepOriginal = "الاحتفاظ بالأصلية",
    imageCompressBefore = "قبل",
    imageCompressAfter = "بعد",
    imageCompressRatio = "نسبة الضغط",
    imageCompressAction = "بدء الضغط",
    imageCompressing = "جارٍ الضغط",
    imageCompressSelectHint = "اختر الصور للضغط",
    imageCompressError = "فشل الضغط",
    imageCompressOriginalLabel = "الأصل",
    imageCompressOriginalSize = "الحفاظ على الحجم",
    imageCompressSelectAll = "تحديد هذا الشهر",
    imageCompressSelected = "تم تحديد الكل",
    commentPlaceholder = "أضف تعليقاً...",
    commentsHeader = "تعليقات",
    commentUser = "أنت",
    noLikes = "لا إعجابات بعد",
    removeLikeTitle = "إزالة من الإعجابات",
    removeLikeMessage = "هل أنت متأكد أنك تريد إزالة هذا العنصر من الإعجابات؟",
    remove = "إزالة",
    send = "إرسال",
    share = "مشاركة",
    comment = "تعليق",
    removeLike = "إزالة الإعجاب",
    avatar = "الصورة الرمزية",
    avatarBoy = "ولد",
    avatarGirl = "بنت",
    commentUserMe = "أنا",
    deleteCommentTitle = "حذف التعليق؟",
    deleteCommentMessage = "هل أنت متأكد أنك تريد حذف هذا التعليق؟",
    copyComment = "نسخ",
    commentCopied = "تم نسخ التعليق",
    holidayNewYear = "رأس السنة الميلادية",
    holidayValentines = "عيد الحب",
    holidayChildrens = "عيد الطفل",
    holidayLaborDay = "عيد العمال",
    holidayNationalDay = "العيد الوطني",
    holidaySpringFestival = "عيد الربيع",
    holidayDragonBoat = "مهرجان قوارب التنين",
    holidayMidAutumn = "عيد منتصف الخريف",
    groupPhotosTitle = "صور جماعية",
    shootingStatsTitle = "رؤى الألبوم",
    shootingStatsYear = "سنة",
    shootingStatsMonth = "شهر",
    shootingStatsSummary = "في %1\$s، قمت بتسجيل %2\$s لحظة.",
    shootingStatsSummaryMonth = "في %1\$s، قمت بتسجيل %2\$s لحظة.",
    shootingStatsItems = "%1\$s صور | %2\$s فيديو",
    shootingStatsVideoDuration = "إجمالي الفيديو: %1\$s دقيقة",
    shootingStatsMovies = "يعادل مشاهدة %1\$s أفلام",
    shootingStatsShortDrama = "يعادل مشاهدة %1\$s دراما قصيرة",
    shootingStatsTvDrama = "يعادل مشاهدة %1\$s حلقة مسلسل",
    shootingStatsScreenshots = "لقطات شاشة",
    shootingStatsSelfies = "صور شخصية",
    shootingStatsMostActiveDay = "اليوم الأكثر نشاطًا: %1\$s (%2\$s عنصر)",
    shootingStatsVideoTitle = "فيديو",
    shootingStatsActiveDayTitle = "يوم نشط",
    shootingStatsLocationTitle = "موقع",
    shootingStatsLocationPlaces = "%1\$s أماكن",
    shootingStatsHeatmapTitle = "خريطة حرارة النشاط",
    shootingStatsHeatmapLess = "أقل",
    shootingStatsHeatmapMore = "أكثر",
    newFolder = "New Folder",
    createNewFolder = "Create New Folder",
    folderName = "Folder Name",
    create = "Create",
    undoSuccess = "Undone",
    readyForNextBatch = "هل أنت مستعد للمجموعة التالية؟ (المتبقي %1\$d عنصر)",
    continueOrganizing = "متابعة التنظيم",
    privacyPolicy = "سياسة الخصوصية",
    termsOfService = "شروط الخدمة",
    agreeToTerms = "أوافق على شروط الخدمة وسياسة الخصوصية",
    manageFilesPermission = "إدارة جميع الملفات",
    manageFilesPermissionDesc = "مطلوب لنقل الصور إلى مجلدات وتنظيم هيكل معرض الصور الخاص بك.",
    currentFolder = "المجلد الحالي",
    openSourceLicenses = "تراخيص المصدر المفتوح"
)

val StringsRu = LocalizedStrings(
    undo = "Отмена",
    clean = "Очистить",
    stats = "Стат.",
    skip = "ОСТАВИТЬ", // Changed from "СОХР." to "ОСТАВИТЬ" (Leave/Keep)
    trash = "УДАЛИТЬ",
    live = "LIVE",
    unknownLocation = "Неизвестно",
    camera = "КАМЕРА",
    location = "МЕСТО",
    iso = "ISO",
    shutter = "ВЫДЕРЖКА",
    date = "ДАТА",
    size = "РАЗМЕР",
    resolution = "РАЗРЕШЕНИЕ",
    filename = "ИМЯ ФАЙЛА",
    settings = "Настройки",
    language = "Язык",
    processed = "Обработано",
    deleted = "Удалено",
    skippedLabel = "Пропущено",
    savedSpace = "Освобождено",
    emptyStateTitle = "Готово!",
    emptyStateSubtitle = "Вы разобрали эту группу медиафайлов.",
    emptyStateButton = "Загрузить еще",
    permissionsNeed = "Нужен доступ к медиафайлам",
    timeSaved = "Сэкономлено времени",
    totalProcessed = "Всего обработано",
    ofGallery = "от галереи",
    savedSpaceRatioFormat = "%1\$s%% (Всего %2\$sGB)",
    pressAgainToExit = "Нажмите еще раз для выхода",
    deleteReviewTitle = "Подтверждение удаления",
    deleteReviewSubtitle = "Выберите элементы для удаления. Невыбранные элементы будут сохранены.",
    cancel = "Отмена",
    delete = "Удалить",
    similar = "Похожие",
    noSimilarPhotosFound = "Похожие фото не найдены",
    scanning = "Сканирование...",
    stop = "Стоп",
    keepSelected = "Сохранить выбранное",
    keepAll = "Сохранить все",
    deleteAll = "Удалить все",
    selectBest = "Выберите лучшее фото.",
    similarPhotosDone = "Все похожие фотографии обработаны!",
    done = "Готово",
    noSimilarPhotos = "Похожие фото не найдены",
    likes = "Лайки",
    viewLikes = "Посмотреть избранное",
    months = listOf("Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь"),
    smartOrganizeTitle = "Умная организация",
    noClustersFound = "Предложений не найдено",
    moveTo = "Переместить в",
    move = "Переместить",
    collapse = "Свернуть",
    viewAll = "Показать все",
    monthly = "Ежемесячно",
    monthlyTitle = "Ежемесячная организация",
    monthlyDoneTitle = "Месяц завершён!",
    monthlyDoneButton = "Назад к месяцам",
    selectLanguage = "Выберите язык",
    back = "Назад",
    privacyTitle = "Политика конфиденциальности",
    privacyButton = "Конфиденциальность",
    privacySection1Title = "Сбор данных",
    privacySection1Content = "Мы получаем доступ к вашим фото и видео только для их организации. Разрешение на доступ к хранилищу требуется только для этого. Мы не собираем личную информацию.",
    privacySection2Title = "Защита конфиденциальности",
    privacySection2Content = "Мы работаем офлайн. Интернет и вход в систему не требуются, мы не отслеживаем действия пользователей и не проводим анализ пользователей.",
    privacySection3Title = "Безопасность данных",
    privacySection3Content = "Ваши данные остаются на устройстве. Вся обработка происходит локально, ваши фото никогда не покидают телефон.",
    privacySection4Title = "Открытый код и аудит",
    privacySection4Content = "photoo — это программное обеспечение с доступным исходным кодом. Вы можете проверить код, чтобы убедиться в соблюдении конфиденциальности. Мы стремимся к прозрачности.",
    onboardingWelcomeTitle = "Добро пожаловать в photoo",
    onboardingWelcomeSubtitle = "Организуйте и сжимайте воспоминания за несколько минут.",
    onboardingNext = "Далее",
    onboardingBack = "Назад",
    onboardingLanguageTitle = "Выберите язык",
    onboardingLanguageSubtitle = "Язык устройства выбран по умолчанию. Можно изменить в любое время.",
    onboardingPermissionTitle = "Доступ к медиа",
    onboardingPermissionSubtitle = "Нужен доступ к фото и видео для организации и сжатия.",
    onboardingPermissionButton = "Разрешить доступ",
    onboardingPermissionGranted = "Доступ предоставлен",
    onboardingStartTitle = "Готово",
    onboardingStartSubtitle = "Можно начать пользоваться photoo.",
    onboardingStartButton = "Начать",
    batchSize = "Размер пакета",
    queueOrder = "Порядок очереди",
    orderRandom = "Случайно",
    orderTime = "Время",
    releaseKept = "Вернуть обработанные",
    releaseKeptDesc = "Вернуть обработанные фото в очередь",
    released = "Возвращено",
    version = "Версия",
    copyright = "©superwatermelon",
    releaseDialogTitle = "Вернуть фото?",
    releaseDialogContent = "Это вернет все обработанные фотографии в очередь. Вы уверены?",
    confirm = "Подтвердить",
    muteVideos = "Без звука для видео и Live Photos",
    soundEffects = "Звуковые эффекты",
    haptics = "Тактильная отдача",
    comboAnimation = "Анимация комбо",
    filterTitle = "Фильтр",
    filterType = "Тип медиа",
    filterFolder = "Папка",
    apply = "Применить",
    filterAll = "Все",
    filterImage = "Фото",
    filterVideo = "Видео",
    filterLive = "Live",
    viewTrash = "Просмотр корзины",
    lowQuality = "Низкое качество",
    blur = "Размыто",
    underexposed = "Недоэкспонировано",
    overexposed = "Переэкспонировано",
    closedEyes = "Закрытые глаза",
    smallFile = "Маленький файл",
    lowResolution = "Низкое разрешение",
    scanLowQuality = "Сканировать низкое качество",
    noLowQualityFound = "Фото низкого качества не найдены",
    lowQualityDone = "Все фото низкого качества обработаны!",
    solidColor = "Сплошной цвет",
    deepOrganizeTitle = "Глубокая организация",
    deepOrganizeScanning = "Сканирование галереи...",
    deepOrganizeComplete = "Сканирование завершено",
    deepOrganizeScanningDesc = "Анализ фото на качество, сходство и события.",
    scanningWait = "Пожалуйста, подождите...",
    scanningDescriptionDetailed = "Это может занять около %d минут в зависимости от размера галереи. Вы можете выйти, и процесс продолжится в фоновом режиме.",
    exit = "Выход",
    similarPhotosSubtitle = "Поиск и удаление дубликатов",
    smartOrganizeSubtitle = "Группировка по событиям и местам",
    lowQualitySubtitle = "Размытые, темные и плохие фото",
    videoCompressTitle = "Сжатие видео",
    videoCompressSubtitle = "Снижение размера с минимальной потерей качества",
    videoCompressWarningTitle = "Предупреждение о качестве",
    videoCompressWarningBody = "Сжатие может немного снизить четкость и битрейт, но большинство видео всё равно хорошо выглядят на телефоне и при отправке. Сначала попробуйте несколько, затем сжимайте пакетно, если всё устраивает.",
    videoCompressTargetLabel = "Целевой битрейт",
    videoCompressBitrateLow = "Меньше размер",
    videoCompressBitrateBalanced = "Баланс",
    videoCompressBitrateHigh = "Четче",
    videoCompressEstimate = "Оценка",
    videoCompressTimes = "Сжато %d раз",
    videoCompressResultTitle = "Сжатие завершено",
    videoCompressResultSaved = "Сэкономлено места",
    videoCompressResultCount = "Сжатые видео",
    videoCompressDeleteOriginal = "Удалить оригиналы",
    videoCompressKeepOriginal = "Оставить оригиналы",
    videoCompressDeleteConfirmTitle = "Удалить оригинальные видео?",
    videoCompressDeleteConfirmBody = "Сжатые версии сохранены. После удаления восстановить нельзя.",
    videoCompressBefore = "Исходный",
    videoCompressAfter = "Сжатый",
    videoCompressRatio = "Коэффициент сжатия",
    videoCompressAction = "Начать сжатие",
    videoCompressing = "Сжатие",
    videoCompressSelectHint = "Выберите видео для сжатия",
    videoCompressError = "Сжатие не удалось",
    imageCompressTitle = "Сжатие фото",
    imageCompressSubtitle = "Сжать фото, чтобы освободить место",
    imageCompressWarningTitle = "Предупреждение о качестве",
    imageCompressWarningBody = "Сжатие снижает качество. Сначала попробуйте несколько фото.",
    imageCompressThresholdLabel = "Порог фильтра",
    videoCompressThresholdLabel = "Порог фильтра",
    imageCompressResultTitle = "Сжатие завершено",
    imageCompressResultSaved = "Сэкономлено места",
    imageCompressResultCount = "Сжато фото",
    imageCompressDeleteOriginal = "Удалить оригиналы",
    imageCompressKeepOriginal = "Оставить оригиналы",
    imageCompressBefore = "До",
    imageCompressAfter = "После",
    imageCompressRatio = "Коэффициент сжатия",
    imageCompressAction = "Начать сжатие",
    imageCompressing = "Сжатие...",
    imageCompressSelectHint = "Выберите фото для сжатия",
    imageCompressError = "Сжатие не удалось",
    imageCompressOriginalLabel = "ОРИГИНАЛ",
    imageCompressOriginalSize = "Сохранить размер",
    imageCompressSelectAll = "Выбрать месяц",
    imageCompressSelected = "Все выбраны",
    commentPlaceholder = "Добавить комментарий...",
    commentsHeader = "Комментарии",
    commentUser = "Вы",
    noLikes = "Нет лайков",
    removeLikeTitle = "Удалить из лайков?",
    removeLikeMessage = "Вы уверены, что хотите удалить этот элемент из лайков?",
    remove = "Удалить",
    send = "Отправить",
    share = "Поделиться",
    comment = "Комментарий",
    removeLike = "Удалить лайк",
    avatar = "Аватар",
    avatarBoy = "Парень",
    avatarGirl = "Девушка",
    commentUserMe = "Я",
    deleteCommentTitle = "Удалить комментарий?",
    deleteCommentMessage = "Вы уверены, что хотите удалить этот комментарий?",
    copyComment = "Копировать",
    commentCopied = "Комментарий скопирован",
    holidayNewYear = "Новый год",
    holidayValentines = "День Святого Валентина",
    holidayChildrens = "День защиты детей",
    holidayLaborDay = "День труда",
    holidayNationalDay = "Национальный праздник",
    holidaySpringFestival = "Праздник весны",
    holidayDragonBoat = "Праздник драконьих лодок",
    holidayMidAutumn = "Праздник середины осени",
    groupPhotosTitle = "Групповые фото",
    filterCompletedTitle = "Фильтр завершен",
    filterCompletedSubtitle = "Вы просмотрели все элементы в %1\$s.",
    reviewAgain = "Просмотреть снова (Освободить все)",
    changeFilter = "Изменить фильтр",
    selectMonth = "Выбрать месяц",
    filterMonth = "Месяц",
    shootingStatsTitle = "Инсайты альбома",
    shootingStatsYear = "Год",
    shootingStatsMonth = "Месяц",
    shootingStatsSummary = "В %1\$s вы записали %2\$s моментов.",
    shootingStatsSummaryMonth = "В %1\$s вы записали %2\$s моментов.",
    shootingStatsItems = "%1\$s Фото | %2\$s Видео",
    shootingStatsVideoDuration = "Всего видео: %1\$s мин",
    shootingStatsMovies = "Эквивалентно просмотру %1\$s фильмов",
    shootingStatsShortDrama = "Эквивалентно просмотру %1\$s серий коротких драм",
    shootingStatsTvDrama = "Эквивалентно просмотру %1\$s серий",
    shootingStatsScreenshots = "Скриншоты",
    shootingStatsSelfies = "Селфи",
    shootingStatsMostActiveDay = "Самый активный день: %1\$s (%2\$s элементов)",
    shootingStatsVideoTitle = "Видео",
    shootingStatsActiveDayTitle = "Активный день",
    shootingStatsLocationTitle = "Место",
    shootingStatsLocationPlaces = "%1\$s Мест",
    shootingStatsHeatmapTitle = "Тепловая карта активности",
    shootingStatsHeatmapLess = "Меньше",
    shootingStatsHeatmapMore = "Больше",
    newFolder = "Новая папка",
    createNewFolder = "Создать новую папку",
    folderName = "Имя папки",
    create = "Создать",
    undoSuccess = "Отменено",
    readyForNextBatch = "Готовы к следующей партии? (осталось %1\$d)",
    continueOrganizing = "Продолжить",
    privacyPolicy = "Политика конфиденциальности",
    termsOfService = "Условия использования",
    agreeToTerms = "Я согласен с Условиями использования и Политикой конфиденциальности",
    manageFilesPermission = "Управление файлами",
    manageFilesPermissionDesc = "Требуется для перемещения фото в папки и организации структуры галереи.",
    currentFolder = "Текущая папка",
    openSourceLicenses = "Лицензии ПО с открытым кодом"
)

fun getStrings(lang: AppLanguage): LocalizedStrings {
    return when (lang) {
        AppLanguage.English -> StringsEn
        AppLanguage.SimplifiedChinese -> StringsZh
        AppLanguage.TraditionalChinese -> StringsZhTw
        AppLanguage.Korean -> StringsKo
        AppLanguage.Japanese -> StringsJa
        AppLanguage.French -> StringsFr
        AppLanguage.German -> StringsDe
        AppLanguage.Italian -> StringsIt
        AppLanguage.Portuguese -> StringsPt
        AppLanguage.Spanish -> StringsEs
        AppLanguage.Russian -> StringsRu
        AppLanguage.Thai -> StringsTh
        AppLanguage.Vietnamese -> StringsVi
        AppLanguage.Indonesian -> StringsId
        AppLanguage.Arabic -> StringsAr
    }
}

val LocalAppStrings = compositionLocalOf { StringsEn }
val LocalAppLanguage = compositionLocalOf { AppLanguage.English }
val LocalHapticsEnabled = compositionLocalOf { true }
